CREATE TABLE IF NOT EXISTS bd_antigua (
    SKU VARCHAR(20),
    `TIPO COLECCION` VARCHAR(50),
    CANAL VARCHAR(50),
    PATAGONIA VARCHAR(50),
    tipo VARCHAR(50),
    Doc VARCHAR(30),
    `Fecha Fact` DATE,
    `año` INT,
    mes INT,
    nom_mes VARCHAR(20),
    Numped VARCHAR(100),
    OrdComp VARCHAR(30),
    Codigo VARCHAR(30),
    `Razon Social` VARCHAR(100),
    `Nombre Corto` VARCHAR(100),
    Ref VARCHAR(20),
    Talla VARCHAR(10),
    Pinta VARCHAR(10),
    Color VARCHAR(30),
    Coleccion VARCHAR(50),
    `Catego Pdto` VARCHAR(50),
    Linea VARCHAR(50),
    Cuento VARCHAR(100),
    `Cant facturada` INT,
    `Valor Fact Ref` DECIMAL(10,2),
    `Desc` DECIMAL(10,2),
    trm DECIMAL(10,2),
    Zona VARCHAR(100),
    ZONA2 VARCHAR(100),
    Vendedor VARCHAR(100),
    Pais VARCHAR(100),
    Ciudad VARCHAR(50),
    Continente VARCHAR(50),
    Estado VARCHAR(50),
    NitoCC VARCHAR(20),
    GRAN_TOTAL DECIMAL(20,2),
    `GRAN TOTAL USD` DECIMAL(20,2),
    `Valor Total` DECIMAL(20,2),
    `Valor Bruto` DECIMAL(20,2),
    `Valor Descuento` DECIMAL(20,2),
    RefExt VARCHAR(100),
    `Clase de Cliente` VARCHAR(100),
    `Costo st Total` DECIMAL(20,2),
    `Categoria 1` VARCHAR(255),
    `Categoria 2` VARCHAR(255),
    `Categoria 3` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
