CREATE TABLE IF NOT EXISTS cartera_nacional (
<<<<<<< HEAD
    NitoCC INT,
=======
    NitoCC VARCHAR(50),
>>>>>>> f116724 (init: estructura Safetti ETL)
    NOMBRE VARCHAR(100),
    Creditos INT,
    Porvencer INT,
    `Ven<30` INT,
    `Ven<60` INT,
    `Ven<90` INT,
    `Ven>90` INT,
    `Ven<120` INT,
    `Ven<150` INT,
    Masde150 INT,
    Total INT,
    DV INT,
    Fecha DATE,
    NFACT INT,
    Fechaini DATE,
    FechaFin DATE,
    DiasFact INT,
    DiasVen INT,
    Direccion VARCHAR(200),
    Telefono VARCHAR(50),
    Ciudades VARCHAR(50),
    Celular VARCHAR(50),
    Zona VARCHAR(50),
    NCodVen INT,
    NombreVendedor VARCHAR(100),
    Clase VARCHAR(100),
    ConcDig VARCHAR(100),
    `Nombre Corto` VARCHAR(50),
    CODIGO VARCHAR(20),
    Voriginal INT,
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;