CREATE TABLE IF NOT EXISTS cartera_exportacion (
    NitoCC VARCHAR(30),
    CODIGO VARCHAR(20),
    NOMBRE VARCHAR(100),
    Creditos INT,
    Porvencer INT,
    `Ven<30` DECIMAL(15,2),
    `Ven<60` DECIMAL(15,2),
    `Ven<90` DECIMAL(15,2),
    `Ven>90` DECIMAL(15,2),
    `Ven<120`DECIMAL(15,2),
    `Ven<150`DECIMAL(15,2),
    Masde150 DECIMAL(15,2),
    Totales DECIMAL(15,2),
    DV INT,
    Fecha DATE,
    NFACT VARCHAR(30),
    `Fechaini-` DATE,
    `FechaFin-` DATE,
    DiasFact INT,
    DiasVen INT,
    Direccion VARCHAR(200),
    Telefono VARCHAR(50),
    Ciudades VARCHAR(50),
    Celular VARCHAR(50),
    NCodVen INT,
    NombreVendedor VARCHAR(100),
    ConcDig VARCHAR(100),
    trm DECIMAL(15,2),
    Voriginal DECIMAL(15,2),
    FSunat VARCHAR(20),
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;