CREATE TABLE IF NOT EXISTS cxp_nacionales (
    CODIGO VARCHAR(20),
    Proveedor VARCHAR(200),
    Ciudad VARCHAR(50),
    NFACT VARCHAR(30),
    Fechaini DATE,
    Fechafin DATE,
    DiasVen INT,
    Credito DECIMAL(15,2),
    Vencidos DECIMAL(15,2),
    `P Ven<30` DECIMAL(15,2),
    `P Ven<60` DECIMAL(15,2),
    `P Ven<90` DECIMAL(15,2),
    `P mas de 90` DECIMAL(15,2),
    Total DECIMAL(15,2),
    nitocc VARCHAR(30),
    CodConcepto VARCHAR(30),
    NomConcepto VARCHAR(100),
    Tipo VARCHAR(30),
    `Nº Entrada` VARCHAR(15),
    Observacion VARCHAR(300),
    codbanco VARCHAR(20),
    tipocta VARCHAR(50),
    numcta VARCHAR(50),
    beneficiario VARCHAR(100),
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;