CREATE TABLE IF NOT EXISTS facturado_real_todos (
    Nfact INT,
    DEV INT,
    Tipo VARCHAR(30),
    `Fecha Fact` DATE,
    año INT,
    Mes INT,
    Codigo INT,
    `Razon Social` VARCHAR(100),
    `Nombre Corto` VARCHAR(50),
    Ref VARCHAR(30),
    Descripcion VARCHAR(100),
    Talla VARCHAR(10),
    Pinta VARCHAR(5),
    Color VARCHAR(20),
    Coleccion VARCHAR(20),
    `Catego Pdto` VARCHAR(50),
    Linea VARCHAR(20),
    Cuento VARCHAR(20),
    `Cant facturada` INT,
    `Valor Fact Ref` DECIMAL(10,2),
    `Desc` INT,
    Vendedor VARCHAR(50),
    NitoCC VARCHAR(20),
    `Valor Desc` DECIMAL(10,2),
    `Costo ST x und` DECIMAL(10,2),
    `Costo ST total` DECIMAL(10,2),
    `Obs en Fact` VARCHAR(100),
    CbarraInt VARCHAR(30),
    CbarraExt VARCHAR(30),
    CbarraMuestras VARCHAR(30),
    desclarga VARCHAR(100),
    TipoDoc VARCHAR(50),
    NomConcepto VARCHAR(100),
    CentroCosto VARCHAR(50),
    Empaque VARCHAR(50),
    TipoConf VARCHAR(50),
    Subcategoria VARCHAR(50),
    Clase VARCHAR(50),
    `Tipo de Cliente` VARCHAR(50),
    Zona VARCHAR(50),
    CodPais VARCHAR(10),
    nompais VARCHAR(50),
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;