CREATE TABLE IF NOT EXISTS facturado_real_todos (
    Nfact VARCHAR(30),
    DEV INT,
    Tipo VARCHAR(30),
    `Fecha Fact` DATE,
    año INT,
    Mes INT,
    Codigo INT,
    `Razon Social` VARCHAR(100),
    `Nombre Corto` VARCHAR(50),
    Ref VARCHAR(30),
    Descripcion VARCHAR(100),
    Talla VARCHAR(10),
    Pinta VARCHAR(5),
    Color VARCHAR(20),
    Coleccion VARCHAR(20),
    `Catego Pdto` VARCHAR(50),
    Linea VARCHAR(20),
    Cuento VARCHAR(20),
    `Cant facturada` INT,
    `Valor Fact Ref` DECIMAL(10,2),
    `Desc` INT,
    Vendedor VARCHAR(50),
    NitoCC VARCHAR(20),
    `Valor Desc` DECIMAL(10,2),
    `Costo ST x und` DECIMAL(10,2),
    `Costo ST total` DECIMAL(10,2),
    `Obs en Fact` VARCHAR(100),
    CbarraInt VARCHAR(30),
    CbarraExt VARCHAR(30),
    CbarraMuestras VARCHAR(30),
    desclarga VARCHAR(100),
    TipoDoc VARCHAR(50),
    NomConcepto VARCHAR(100),
    CentroCosto VARCHAR(50),
    Empaque VARCHAR(50),
    TipoConf VARCHAR(50),
    Subcategoria VARCHAR(50),
    Clase VARCHAR(50),
    `Tipo de Cliente` VARCHAR(50),
    Zona VARCHAR(50),
    CodPais VARCHAR(10),
    nompais VARCHAR(50),
    `Fecha Fact` DATE,
    Numped VARCHAR(30),
    OrdComp VARCHAR(30),
    `Razon Social` VARCHAR(100),
    `Nombre Corto` VARCHAR(200),
    Codigo VARCHAR(10),
    Ref VARCHAR(10),
    Talla VARCHAR(10),
    Pinta VARCHAR(10),
    `Cant facturada` INT,
    Color VARCHAR(25),
    Coleccion VARCHAR(20),
    `Catego Pdto` VARCHAR(30),
    Linea VARCHAR(10),
    Cuento VARCHAR(20),
    `Valor Fact Ref` DECIMAL(15,2),
    `Desc` DECIMAL(5,2),
    trm DECIMAL(10,2),
    Zona VARCHAR(50),
    Vendedor VARCHAR(50),
    Pais VARCHAR(50),
    Ciudad VARCHAR(50),
    Continente VARCHAR(30),
    Estado VARCHAR(30),
    zipcode VARCHAR(30),
    VendedorRep VARCHAR(30),
    NitoCC VARCHAR(20),
    tipo VARCHAR(15),
    Doc VARCHAR(20),
    `Valor Total` DECIMAL(15,2),
    `Valor Bruto` DECIMAL(15,2),
    `Valor Descuento` DECIMAL(15,2),
    `Costo st` DECIMAL(15,2),
    `Costo st Total` DECIMAL(15,2),
    CostoProm DECIMAL(15,2),
    CostoPromTotal DECIMAL(15,2),
    UltCostoLotedpc DECIMAL(15,2),
    `UltCostoLotedpc Total` DECIMAL(15,2),
    `Margen $` DECIMAL(15,2),
    `Margen UltCostoLotedpc $` DECIMAL(15,2),
    `Valor Total Dolares` DECIMAL(15,2),
    pmarund DECIMAL(20,2),
    pmarundU DECIMAL(20,2),
    RefExt VARCHAR(200),
    Descposi VARCHAR(200),
    RsTalla VARCHAR(30),
    ConDig VARCHAR(15),
    nombreConDig VARCHAR(200),
    TipoR VARCHAR(30),
    `Clase de CLiente` VARCHAR(100),
    desclarga VARCHAR(200),
    TipoConf VARCHAR(200),
    CentroCosto VARCHAR(50),
    SubCat VARCHAR(150),
    PrecioPM DECIMAL(15,2),
    RefEquivalente VARCHAR(30),
    Codpais VARCHAR(10),
    nompais VARCHAR(30),
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;