CREATE TABLE IF NOT EXISTS inventario_pos(
    Ref VARCHAR(20),
    Pinta VARCHAR(10),
    Color VARCHAR(20),
    talla VARCHAR(10),
    Cant INT,
    MercTrans INT,
    Coleccion VARCHAR(30),
    Cuento VARCHAR(50),
    Linea VARCHAR(20),
    Descripcion VARCHAR(100),
    SubCategoria VARCHAR(100),
    Punto VARCHAR(100),
    UltPrecio DECIMAL(20,2),
    UltFechaDesp DATE,
    `Dias Inv` INT,
    OrdTalla INT,
    `Primer Fecha Ent` DATE,
    `Dias Inv Primer Fecha Ent` INT,
    `Primer Fecha TrasRec` DATE,
    RefExt VARCHAR(30),
    `Precio de venta al por mayor sin IVA` DECIMAL(20,2),
    `Valor Total` DECIMAL(20,2),
    CostoFT DECIMAL(20,2),
    TipoConf VARCHAR(30),
    Instrucciones VARCHAR(255),
    desclarga VARCHAR(200),
    DescL INT,
    DescL2 INT,
    DescL3 INT,
    DescL4 INT,
    DescL5 INT,
    DescL6 INT,
    DescL7 INT,
    DescL8 INT,
    DescL9 INT,
    DescL10 INT,
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;