CREATE TABLE IF NOT EXISTS inventario_disponible_bodega_terminado (
    Ref VARCHAR(20),
    refext VARCHAR(100),
    Pinta VARCHAR(10),
    Colores VARCHAR(50),
    Coleccion VARCHAR(50),
    Linea VARCHAR(30),
    Cuento VARCHAR(50),
    Descripcion VARCHAR(50),
    CANT INT,
    InvBod95a99 INT,
    CANTPosint INT,
    Talla VARCHAR(5),
    PrecioPM DECIMAL(15,5),
    PrecioPP DECIMAL(15,5),
    Precio2 DECIMAL(15,5),
    Precio3 DECIMAL(15,5),
    Precio4 DECIMAL(15,5),
    costo INT,
    TipoConf VARCHAR(50),
    DescLarga VARCHAR(200),
    DescSubcategoria VARCHAR(100),
    InvMin INT,
    InvMax INT,
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;