CREATE TABLE IF NOT EXISTS telas_en_bodega (
    Cod VARCHAR(20),
    Componente VARCHAR(50),
    Especifico VARCHAR(50),
    Ancho DECIMAL(10,2),
    ML DECIMAL(10,2),
    M2 DECIMAL(10,3),
    Costo DECIMAL(10,2),
    Colores VARCHAR(30),
    Proveedor VARCHAR(100),
    BodInt INT,
    Activo INT,
    Rend INT,
    K DECIMAL(10,2),
    `Fecha Inv` DATE,
    FDev DATE,
    FAjuste DATE,
    FEntProv DATE,
    FEntProc DATE,
    `FEntPlan o EntCorte` DATE,
    FSalProv DATE,
    `FSalPlanta o SalCorte` DATE,
    FSalProc DATE,
    FFact DATE,
    fecha_operacion DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;