CREATE TABLE IF NOT EXISTS ventas_pos3 (
    `Punto de Venta` VARCHAR(100),
    Nfact VARCHAR(25),
    Dev INT,
    Tipo VARCHAR(30),
    Forma VARCHAR(10),
    `Fecha Fact` DATE,
    `año` INT,
    Mes INT,
    Codigo VARCHAR(30),
    Cliente VARCHAR(100),
    Ref VARCHAR(30),
    Descripcion VARCHAR(100),
    Talla VARCHAR(10),
    Pinta VARCHAR(10),
    Color VARCHAR(30),
    Coleccion VARCHAR(30),
    `Catego Pdto` VARCHAR(50),
    Linea VARCHAR(25),
    Cuento VARCHAR(50),
    `Cant facturada` INT,
    `Precio bruto con Iva x und` DECIMAL(18,2),
    `Porcentaje Desc` DECIMAL(5,2),
    `Full o con Desc` VARCHAR(20),
    Vendedor VARCHAR(100),
    NitoCC VARCHAR(30),
    `Total Base gravable sin flete` DECIMAL(18,2),
    `Total Valor neto sin flete` DECIMAL(18,2),
    `Total valor Desc con Iva` DECIMAL(18,2),
    `Costo ST x und` DECIMAL(10,2),
    `Costo ST Total` DECIMAL(10,2),
    `Margen $` DECIMAL(20,2),
    pmarundTotal DECIMAL(20,2),
    pmarundReal DECIMAL(20,2),
    `Precio neto sin flete x und` DECIMAL(20,2),
    `Base gravable sin flete x und` DECIMAL(20,2),
    `Iva sin flete x und` DECIMAL(20,2),
    `Total valor Desc sin Iva` DECIMAL(20,2),
    Convenio VARCHAR(30),
    CTPUC VARCHAR(30),
    `Concepto Dig` VARCHAR(150),
    `Tipo Fabricado o Comprado` VARCHAR(2),
    fecharealmov DATE,
    ncodvend VARCHAR(15),
    TipoConf VARCHAR(30),
    ciudad VARCHAR(30),
    Barrio VARCHAR(100),
    SubCat VARCHAR(50),
    ZonaTienda VARCHAR(30),
    CiudadTienda VARCHAR(30),
    PreciosinIPC DECIMAL(18,2),
    `Valor IPC` DECIMAL(18,2),
    IPC DECIMAL(3,1),
    RefExt VARCHAR(50),
    Numped VARCHAR(50),
    PuntoFact VARCHAR(50),
    Instrucciones VARCHAR(255),
    CodT VARCHAR(20),
    `Concepto de Pago` VARCHAR(100),
    NomProm VARCHAR(30)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;